export default [
  {
    name: '成员管理',
    icon: 'TeamOutlined',
    path: '/web/members',
    access: 'route',
    permission: 'web.member.paginate',
    component: '@/pages/Web/Member/Paginate',
  },
  {
    name: '轮播管理',
    icon: 'SoundOutlined',
    path: '/web/banners',
    access: 'route',
    permission: 'web.banner.paginate',
    component: '@/pages/Web/Banner/Paginate',
  },
  {
    name: '菜单管理',
    icon: 'PayCircleOutlined',
    path: '/web/menus',
    access: 'route',
    permission: 'web.menu.paginate',
    component: '@/pages/Web/Menu/Paginate',
  },
  {
    name: '职位管理',
    icon: 'KeyOutlined',
    path: '/web/titles',
    access: 'route',
    permission: 'web.title.paginate',
    component: '@/pages/Web/Title/Paginate',
  },
  {
    name: '营业时间',
    icon: 'FieldTimeOutlined',
    path: '/web/times',
    access: 'route',
    permission: 'web.time.paginate',
    component: '@/pages/Web/Time/Paginate',
  },
  {
    name: '站点设置',
    icon: 'SettingOutlined',
    path: '/web/setting',
    access: 'route',
    permission: 'web.setting.list',
    component: '@/pages/Web/Setting',
  },
];
